### PR TITLE
Make Homepage responsive on mobile

### PR DESCRIPTION
**Pull request by mandaputtra**
So without HTML Head tag Bulma aren't responsive on chrome.  It looks like this now on mobile.

<a href="https://ibb.co/sVZcHqK">Screenshot-from-2019-07-28-17-23-57</a>

### CODE REVIEW

**Comment by yamalight** [comment]
So, _that's_ what the problem was! Thank you for figuring it out! ❤️ 

One small request - could you please use [custom document](https://github.com/zeit/next.js/#custom-document) in next.js to add Head instead of using a separate component? This will add it too all pages without having to worry about manually doing it 🤔

**Comment by mandaputtra** [comment]
Oh okay, lol. I never use React before sorry.

**Comment by yamalight** [comment]
No worries, thank you for your contribution!
And that's a next.js-specific thing, not react :)

**Comment by mandaputtra** [comment]
Updated :smile:

**Comment by yamalight** [comment]
Looks great, thank you! ❤️

**Pull request merged**
