### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by 8HoLoN**
Switch theme to save eyes.

### CODE REVIEW

**Comment by yamalight** [comment]
@8HoLoN this makes it dark for everyone - which is not ideal. Could you please add either OS theme detection, or a simple toggle (with default to white theme)?

**Review by yamalight — CHANGES_REQUESTED** [review]
@8HoLoN this makes it dark for everyone - which is not ideal. Could you please add either OS theme detection, or a simple toggle (with default to white theme)?

**Comment by 8HoLoN** [comment]
OK I did a switch feature with default to bright.

**Review by yamalight — CHANGES_REQUESTED** [review]
Aight, that looks almost perfect.
Two more small requests:
- Please make sure `yarn analyze:lint` passes for your new code (it's my fault for not adding that to PR checks, please bear with me 😅 )
- Please persist theme choice on reload (currently resets to system default even if user changed it manually)

**Comment by 8HoLoN** [comment]
OK, done.

**Review by yamalight — CHANGES_REQUESTED** [review]
Sweet, we're nearly there!
It now persist the theme once you switch - but it still doesn't defaults to system theme.
Could you please address this last thing and I'll merge it :)

**Comment by yamalight** [comment]
@8HoLoN looks great now! could you please resolve package.json conflict? I'll merge it as soon as you do :)

**Comment by yamalight** [comment]
I've cherry-picked the changes into dev branch with some minor tweaks. Will deploy soon. 
Thanks for your work!

**Comment by 8HoLoN** [comment]
ahah thank, I was also merging it but you were faster than me!

**Pull request closed without merging**
