### PR TITLE
fix:navbar hidden on mobile

### LINKED ISSUE #2: Navbar not showing on mobile
The navbar is not usable on mobile because Bulma automatically hides the div with the `.navbar-menu` class. 

https://bulma.io/documentation/components/navbar/

### PR DESCRIPTION
**Pull request by mandaputtra**
Fix #2

### CODE REVIEW

**Comment by yamalight** [comment]
@mandaputtra thanks for the PR, but I would prefer to have a proper toggle (see Toggle bit of [bulma docs](https://bulma.io/documentation/components/navbar/#navbar-menu)) for the time when we add more sections to the website

**Comment by mandaputtra** [comment]
Okay

**Comment by mandaputtra** [comment]
Updated :+1:

**Comment by yamalight** [comment]
@mandaputtra awesome, thank you so much! ❤️

**Pull request merged**
